name: Pylint

on: 
  push:
    branches:
    - main
  pull_request:
    branches:
    - main


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Python version
      run: |
        python3.7 --version
    - name: Test color
      uses: dorny/test-reporter@v1
      with:
        name: Unittest
        path: "**/UnitTestdre2.py"
        reporter: dotnet-trx
        fail-on-error: true
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py')
